name: Build Nukkit Plugin

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Compile Plugin
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Download latest Nukkit
      run: |
        mkdir -p libs
        curl -L -o libs/nukkit.jar https://repo.opencollab.dev/maven-snapshots/cn/nukkit/nukkit/1.0-SNAPSHOT/nukkit-1.0-20251001.065813-1220.jar

    - name: Create build directories
      run: mkdir -p build/classes

    - name: Compile Java sources
      run: |
        javac -cp "libs/nukkit.jar" -d build/classes $(find src -name "*.java")

    - name: Copy plugin.yml and config.yml
      run: |
        mkdir -p build/classes/resources
        cp plugin.yml build/classes/
        cp config.yml build/classes/

    - name: Create JAR
      run: |
        cd build/classes
        jar cf ../../CustomEnchantments.jar *
        cd ../..

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CustomEnchantments
        path: CustomEnchantments.jar
